### PR TITLE
added more social media displays

### PR DESCRIPTION
**Pull request by ngmhprogramming**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
- added more displays to the social media section

- [Preview](https://ngmhprogramming.github.io/gci18.fossasia.org/)

## Description / Changes
- added flickr photo slideshow
- added google+ badge
- added github profile card

### Before:
Before

### After:
After

- - - - - - - - - - - -

### CODE REVIEW

**Comment by abishekvashok** [comment]
Can you make them of the same width

**Comment by ngmhprogramming** [comment]
ok i will do that

**Comment by ngmhprogramming** [comment]
the width is actually the same

i measured it using this

    $('.social-media-widget').each(function(i, obj) {
        console.log(obj.getBoundingClientRect().width);
    });

and it gives the same width for all 7 elements

**Comment by ngmhprogramming** [comment]
i realised i may not be able to do that as even though the social-media-widget div is the same size, i cannot make the content inside the same width / height as it is dependent on what the website serves me and i cannot change that

**Comment by ngmhprogramming** [comment]
i do not think more can be done to make it the same width

**Comment by sarnava1** [comment]
I think then this is okay @jogendra

**Comment by ngmhprogramming** [comment]
can you please merge this pr if there's nothing else to be done

**Pull request merged**
