### PR TITLE
Fixes #129 : Added more social icons

### LINKED ISSUE #129: More Social Links needed In Social Media Section
**Actual Behaviour**

Only few certain links present

**Expected Behaviour**

All should be there

**Steps to reproduce it**

Add them

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by saarthakchats**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
- Fixes #129 
- [Preview Link](https://saarthakchats.github.io/gci1/)
## Description / Changes
- Added Linkedin
- Added Flickr
- Added Google Plus
- Added these links to social section and also footer
- Removed unnecessary styles to make code more consistent and smaller

### CODE REVIEW

**Comment by saarthakchats** [comment]
@simsausaurabh @liveHarshit @abishekvashok
Please review and merge 😄

**Comment by sk9331657** [comment]
@saarthakchats  Preview link is not working.

**Comment by saarthakchats** [comment]
I changed it @sk9331657

**Comment by saarthakchats** [comment]
Check now @sk9331657 @liveHarshit

**Comment by saarthakchats** [comment]
@liveHarshit 
Added to footer also

**Comment by liveHarshit** [comment]
The position is not correct,  place it after introduction. There is too much gap between the section and video.

**Comment by sk9331657** [comment]
@saarthakchats  Also if you can fix, fix the image in videos section. That is out of box.

**Comment by saarthakchats** [comment]
@sk9331657 Done 👍

**Pull request closed without merging**
