### PR TITLE
Added a few Mentors

### LINKED ISSUE #635: Add missing mentors to website
List of Mentors
* [x] Jogendra | Kumar
* [ ] Wei Tat | Chung
* [x] Shubham | Gupta
* [ ] Shubham | Kumar
* [ ] Soong Chee | Gi
* [x] Akshat | Garg
* [ ] Abhijeet Singh | Khangarot
* [ ] Tarun | Kumar
* [x] Abishek | V Ashok
* [ ] SARNAVA | KONAR
* [ ] Eden | D
* [ ] Harshit | Khandelwal
* [ ] Hong Phuc | Dang
* [x] Akshat | Jain
* [ ] simranpreet | kaur
* [ ] ROHIT | POTTER
* [ ] Nikit | Bhandari
* [ ] Priyanshu | Khandelwal
* [ ] André | Rebentisch
* [ ] Sanskar | Jethi
* [x] Anshuman | Verma
* [ ] Mayank | Vaidya
* [ ] THIYAGARAJ | T
* [ ] Prateek | Chanda
* [ ] Shubham | Kumar Singh
* [x] Arundhati | Gupta
* [ ] Chashmeet | Singh
* [ ] Madhushanka | Padmal
* [ ] Abhinav | Raj
* [ ] Praveen | Ojha
* [ ] Harsh | Patel
* [ ] Anup | Panwar
* [ ] Praduman | Singh
* [ ] Sridhar | Jajoo
* [ ] Mohit | Sharma
* [ ] Suneet | Srivastava
* [ ] Dilpreet | Singh
* [ ] Rupav | Jain
* [ ] Pranjal | Paliwal

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://nishithp2004.github.io/gci18.fossasia.org)

- Fixes #635 #96 

## Description / Changes
I have added the following Mentors to the site:
* T Thiyagaraj 
* Chung Wei Tat
* Abhijeet Singh
* Simranpreet Kaur
* Rupav Jain
* Suneet Srivastava
* Anup Kumar Panwar
* Praveen Ojha
* Chashmeet Singh
* Mayank Vaidya
* Eden D
*  André Rebentisch
* Madhushanka Padmal
* Abhinav Raj
*  Harsh Patel
* Praduman Singh
* Dilpreet Singh
* Pranjal Paliwal
* Hon Nguyen

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by NishithP2004** [comment]
Please add WIP tag , I’ll tell when it’s done.

**Comment by NishithP2004** [comment]
WIP

**Comment by mariobehling** [comment]
Please only add devs as mentors who are listed in the issue tracker. Some people are really doing awesome work and help newbies, but they are not mentors in the programs yet. Most mentors will have contributed in development programs or won the Codeheat contest. So, there is usually some engagement or connection through events. There might be exceptions but they are rare. We hope that some of the fantastic contributors like Yash can be mentors in future. So, hope everyone keeps contributing.

**Comment by NishithP2004** [comment]
I’m squashing the commits

**Comment by prateekiiest** [comment]
Make the issue name [WIP] if you want to add more mentors here

**Comment by NishithP2004** [comment]
@nikit19 @abishekvashok @SIMRAN1 Please merge.

**Comment by NishithP2004** [comment]
I have successfully added 10 mentors.

**Comment by NishithP2004** [comment]
Please merge

**Comment by prateekiiest** [comment]
@mariobehling @nikit19 
Please have a look at it too.

**Comment by NishithP2004** [comment]
I have successfully added all the mentors mentioned in the issue tracker, please merge. @mariobehling @abishekvashok @AnupKumarPanwar @Masquerade0097 @SIMRAN1 @prateekiiest

**Comment by NishithP2004** [comment]
Please close both the issues while merging.

**Comment by NishithP2004** [comment]
`@mariobehling Please review `

**Comment by NishithP2004** [comment]
@mariobehling need a review.

**Comment by NishithP2004** [comment]
`PLEASE MERGE` @mariobehling

**Pull request merged**
