### PR TITLE
Fixed #62 Added videos section 

### LINKED ISSUE #62: Add a videos section.
**Actual Behaviour**

No space for works of students.

**Expected Behaviour**

Add a videos section.

**Would you like to work on the issue?**

Yes. I am working.

### PR DESCRIPTION
**Pull request by STEdirisuriya**
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Fixes https://github.com/fossasia/gci18.fossasia.org/issues/62
- https://stedirisuriya.github.io/gci18.fossasia.org/

## Description / Changes
I added a videos section and added one of my video into it.

image

### CODE REVIEW

**Comment by tabesin** [comment]
@fragm3 that feature is in this particular case on a different level and would require to hack the theme presets.

On fetching the YT preview pictures see 
https://codeshare.co.uk/blog/how-to-get-the-youtube-thumbnail-preview-image-from-a-video/

**Comment by STEdirisuriya** [comment]
@sarnava1 No, when adding video it will be adjustable. Three videos can insert into a row.

**Comment by STEdirisuriya** [comment]
@fragm3 Isn't it make slower the website?

**Comment by fragm3** [comment]
@STEdirisuriya Lets not use embedding for now, Remove `img/videos/video.png` not required anywhere.

**Comment by STEdirisuriya** [comment]
> @fragm3 that feature is in this particular case on a different level and would require to hack the theme presets.
> 
> On fetching the YT preview pictures see
> https://codeshare.co.uk/blog/how-to-get-the-youtube-thumbnail-preview-image-from-a-video/

You said method is not working for me. 
image
See here, is there any mistake?

**Comment by fragm3** [comment]
@STEdirisuriya your method is fine, Remove `img/videos/video.png` not required anywhere. We are good to go then.

**Comment by STEdirisuriya** [comment]
@fragm3 @tabesin It's not working with that code. 
image

Am I use my method for this?

**Comment by STEdirisuriya** [comment]
@fragm3 @tabesin Now it's fine.

**Comment by abishekvashok** [comment]
Task id: https://codein.withgoogle.com/dashboard/task-instances/5135937857126400/

**Pull request merged**
