### PR TITLE
Remove stock templates and enhance sites UI (#172)

### PR DESCRIPTION
**Pull request by venkateshdb**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<93>`
- Preview Link : https://venkateshdb.github.io/gci18.fossasia.org/#top
-

previous
> # now
now

### CODE REVIEW

**Comment by venkateshdb** [comment]
pls merge this pull request for now, i will do any changes to it afterwards.

**Comment by venkateshdb** [comment]
I don't see any conflict

**Comment by fragm3** [comment]
@venkateshdb You have done multiple changes(older font looks better), without linking the PR to issue. Create 1 PR for 1 issue only, its faster to review and keep track of work.

**Comment by venkateshdb** [comment]
This PR solves these issue #180 #177 . Pls merge the PR and I will open and issue for regarding change of font and some more changes that needs to be done.

**Comment by venkateshdb** [comment]
So you won't merge this pull request

**Comment by jogendra** [comment]
@venkateshdb PR cannot be merged on your sentimental. Please respect the mentor's feedback. If your PR is not fulfilling the requirements, it cannot be merged, Simple as that. Why do you working on an issue that was assigned to someone others?

**Comment by YashKumarVerma** [comment]
Can we close the pr @venkateshdb

**Comment by akshatnitd** [comment]
@venkateshdb Should I close this PR?

**Comment by venkateshdb** [comment]
Yes, you can

**Pull request closed without merging**
