### PR TITLE
Improve student's projects Section

### LINKED ISSUE #388: Enhance Student's Projects Section
# Improve Student's Projects Section and add project . 

**Would you like to work on the issue?**

Yes , I would work on this .

### PR DESCRIPTION
**Pull request by KSNINJA**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://ksninja.github.io/gci18.fossasia.org/students_projects.html)

- Fixes #388

## Description / Changes
Enhanced Student's projects section and also added a project .

### Before:
image

### After:
image

- - - - - - - - - - - -

### CODE REVIEW

**Comment by KSNINJA** [comment]
Yes , I just checked the log .

**Comment by KSNINJA** [comment]
@jogendra Why do we want to remove the links from nav-bar?

**Comment by jogendra** [comment]
@KSNINJA We have links for home page so they don't make sense. Also, they belong to the home page only.

**Comment by abishekvashok** [comment]
Was these data added after you talked to each of these students?

**Comment by KSNINJA** [comment]
Not to each student . Just one when I wanted to have some info about his project .

**Comment by KSNINJA** [comment]
@jogendra I have committed the changes about the navigation bar 
@abishekvashok I haven't received consents from 2 persons (@saarthakchats  and @pythongiant ).
    They haven't read my message yet . Other 3 have given me allowances .

**Pull request merged**
