### PR TITLE
[REVIEW NEEDED] Removed external links

### LINKED ISSUE #638: Fix CSS and avoid external CSS of other services
The website had included external CSS. We should not share data with other services pro-actively. I deleted the services. We need help now to re-connect the original CSS with the current website.

### LINKED ISSUE #639: Deletion of external services e.g. jquery links broke site
Goal: Please fix the broken parts and only include links and Javascript etc. internally.

### PR DESCRIPTION
**Pull request by Sangatdas**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://sangatdas.github.io/gci18.fossasia.org/)

- Fixes #638 
- Fixes #639 

## Description / Changes
Removed CDN links and added paths to local libraries.

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by NishithP2004** [comment]
@Sangatdas BTW why have you added a Fontawesome license?

**Comment by NishithP2004** [comment]
Please remove /18 /17 /16 /15 , others look good!

**Comment by NishithP2004** [comment]
@Sangatdas

**Comment by NishithP2004** [comment]
Requesting a review , his work looks great .Please have a look @abishekvashok @jogendra @rpotter12

**Comment by NishithP2004** [comment]
@Sangatdas Please squash your commits as well.:)

**Comment by Sangatdas** [comment]
@NishithP2004 Made requested changes.

**Comment by NishithP2004** [comment]
> 0f18640f-59c8-4f57-9dc4-2fef3e136fd9
> Please remove /18 /17 /16 /15 , others look good!

@Sangatdas This is not yet changed..

**Comment by Sangatdas** [comment]
@NishithP2004 Can you check the Preview link? Because it's showing correct.

**Comment by NishithP2004** [comment]
@abishekvashok @mariobehling Requesting a review.

**Comment by NishithP2004** [comment]
@rpotter12 Please merge it as the site needs to be fixed.

**Comment by NishithP2004** [comment]
@rpotter12 I believe that the issue is not with his code, because it is not the original site and hence leads to sangatdas.github.io which is an empty page as he has no portfolio...

**Comment by NishithP2004** [comment]
@rpotter12 the required changes work only on the original site (according to me)

**Comment by Sangatdas** [comment]
Agreed with @NishithP2004

**Pull request merged**
