### PR TITLE
Added project to GCI18 Projects Section

### PR DESCRIPTION
**Pull request by aryanguls**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](url)

- Fixes #<Issue Number>

## Description / Changes
For the purpose of this merge request I have added my blog to the projects section in the GCI18 website. 
Link to the Blog : https://aryanguls.wordpress.com/2020/01/04/google-code-in-my-open-source-journey/

- - - - - - - - - - - -

### CODE REVIEW

**Comment by aryanguls** [comment]
@rpotter12 please review the above merge request.

**Review by NishithP2004 — CHANGES_REQUESTED** [review]
You have to add the project to the **GCI 19** site and not this.

**Comment by aryanguls** [comment]
Oh sorry I guess there must have been a mistake made. Thanks @NishithP2004 .

**Comment by NishithP2004** [comment]
Link to [Repo](https://gitlab.com/fossasia/gci19-fossasia-org)

**Pull request closed without merging**
