### PR TITLE
Added the picture and about me to the repo

### PR DESCRIPTION
**Pull request by abhinavraj0123456789**
Issue number: 33
Detail describing things done in PR: In this PR the picture is added to "img" folder and student details is added into the file "students.yml" inside the "data" folder.
Link to website: https://github.com/abhinavraj0123456789/gci18.fossasia.org

### CODE REVIEW

**Comment by sarnava1** [comment]
@abhinavraj0123456789 please do follow the style which @fragm3 suggested to you. You can also look at the PR template of meilix-generator or SUSI.AI to know how you should open a PR.

**Comment by sarnava1** [comment]
LGTM the changes you have made.

**Comment by fragm3** [comment]
@abhinavraj0123456789 Link Issue properly, it should be a anchor link to issue #33 (like this). Also add your GitHub website as said by @sk9331657

**Comment by tabesin** [comment]
Best Practice is to provide Screenshots before after or a link to your deployed web site.

As this change is trivial one could also accept it without. However there are now conflicting files. So please rebase.

**Comment by abishekvashok** [comment]
Please resolve conflicts to get this merged. Thanks

**Comment by jogendra** [comment]
I am closing this PR because of inactivity of PR author. Feel free to open if you still want to work on this. thanks

**Pull request closed without merging**
