### PR TITLE
Added smooth scrolling feature when clicked on Navbar elements

### LINKED ISSUE #357: Add smooth scrolling when clicked on Navbar elements.
**Actual Behaviour**

When clicked on the elements of Navbar it directly jumbs to that section.

**Expected Behaviour**
Instead of directly jumbing to that section, we can add smooth scrolling effect to make it look better.

**Steps to reproduce it**

1) Go on https://gci18.fossasia.org/
2) Click on any element of Navbar 

**Would you like to work on the issue?**
Yes, I would like to work on the issue.

### PR DESCRIPTION
**Pull request by sahilsaha7773**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
# Changes done in this Pull Request

- [Preview Link](https://sahilsaha7773.github.io/)

- Fixes #357 
## Description / Changes
I have added the smooth scrolling feature.
- Edited the index.html file to add smooth scrolling to all links.

### CODE REVIEW

**Comment by sahilsaha7773** [comment]
I have increased the time now

**Comment by sahilsaha7773** [comment]
It will take 2 seconds to scroll to a specific part

**Comment by sarnava1** [comment]
LGTM

**Comment by sahilsaha7773** [comment]
Thanks

**Comment by sahilsaha7773** [comment]
Please merge

**Pull request merged**
