### PR TITLE
Improve Navigation Bar

### LINKED ISSUE #461: Top menu text is too small and hard to read. Please revert to original design
Top text is too small and hard to read. Please revert to original design

### PR DESCRIPTION
**Pull request by KSNINJA**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://ksninja.github.io/gci18.fossasia.org/)

- Fixes #461 

## Description / Changes
Added new design for the navigation bar  . 
The image in the slide - "WE ARE FOSSASIA" was unreadable due to the multicolour bright background . So , I changed one slide .

### Before:
image

### After:
image

- - - - - - - - - - - -

### CODE REVIEW

**Comment by AppleC4T** [comment]
On the Projects page the navbar blends with the background until the user starts scrolling. It would be nice if you could make an exception for that page. Rest looks good to me. 👍 
image

**Comment by KSNINJA** [comment]
I want to add a js file specifically to the index.html. So,  I am linking it in the footer.  But i dont want that file in the students_projects.html. So,  I created a separate footer.

**Comment by fragm3** [comment]
@KSNINJA I can't find any difference in the footer, why are you creating `_includes/footer-pages.html`. This would mean there are 2 footers doing exactly same stuff. This PR is nav bar specific, let it be that way only.

**Comment by abishekvashok** [comment]
Thanks

**Pull request merged**
