### PR TITLE
[Fixed #74] - Create FOSSASIA Project Section

### LINKED ISSUE #74: Create FOSSASIA Project Section
**Actual Behaviour**

Currently, not present

**Expected Behaviour**

Create FOSSASIA Project Section in https://gci18.fossasia.org/ after mentor section.
Add 1 FOSSASIA open source project description.
See: https://gci17.fossasia.org/ for reference(project section of FOSSASIA after Students Projects)

**Screenshots of the issue**

screenshot 2018-10-27 at 4 35 29 pm

**Would you like to work on the issue?**

Any GCI Participant

### PR DESCRIPTION
**Pull request by STEdirisuriya**
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
- https://github.com/fossasia/gci18.fossasia.org/issues/74
- https://stedirisuriya.github.io/gci18.fossasia.org/

## Description / Changes
I added 1 FOSSASIA open source project description as the issue.

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
@tstreamDOTh Rather than adding a slider it's look good when projects add one by one down. What is the other's opinion about that? @fragm3

**Comment by STEdirisuriya** [comment]
@sarnava1 It's made due to another PR already merged. You can see it's on the main page as well.

**Comment by STEdirisuriya** [comment]
@fragm3 I added a button for try.

**Comment by STEdirisuriya** [comment]
image

**Comment by jogendra** [comment]
@STEdirisuriya chat.susi.ai is not the only SUSI project. Please add links for others SUSI projects eg. Android, iOS, Skill CMS, Server etc

**Comment by STEdirisuriya** [comment]
@jogendra Please look the related issue to this PR. It said only to add one project. I think it because giving other gci students to take part in this work. @fragm3 Am I correct? Please could you merge this?

**Comment by fragm3** [comment]
@tstreamDOTh @jogendra please share your thoughts

**Comment by STEdirisuriya** [comment]
@fargm3 @jogendra Thank you!

**Pull request merged**
