### PR TITLE
thankyou.js: Add Marathi Translation & Add My Profile For Student

### PR DESCRIPTION
**Pull request by AryanKedare**
- [ ] Included a Preview link and screenshot showing after and before the changes.
- [ ] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://aryankedare.github.io/gci18.fossasia.org/)

- Fixes #

### After:

screenshot from 2018-11-07 09-51-34

- - - - - - - - - - - -

### CODE REVIEW

**Comment by AryanKedare** [comment]
Added

**Comment by sk9331657** [comment]
@A

> Added

Add the issue number and not the PR number.

**Comment by AryanKedare** [comment]
Where i can find the issue number?

**Comment by sk9331657** [comment]
> Where i can find the issue number?

https://github.com/fossasia/gci18.fossasia.org/issues

**Comment by AryanKedare** [comment]
Done

**Comment by sk9331657** [comment]
> Done

You are referencing wrong issue number since the issue you referenced is for translating GCI website in different languages.Add the right issue number or create the new issue if not present.

**Comment by AryanKedare** [comment]
I guess there is no issues for thankyou.js and student

**Comment by STEdirisuriya** [comment]
Use to two PRs to do this.

**Pull request merged**
