### PR TITLE
Added Gitter(social media) in index.html

### PR DESCRIPTION
**Pull request by Ashwanth7230**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://github.com/Ashwanth7230/gci18.fossasia.org/blob/master/index.html)

- Fixes #575

## Description / Changes
Added Gitter(social media) in index.html

### After:
image

- - - - - - - - - - - -

### CODE REVIEW

**Comment by Ashwanth7230** [comment]
then which screenshot should i provide

**Comment by Ashwanth7230** [comment]
updated preview link

**Comment by Ashwanth7230** [comment]
is screenshot optional

**Comment by pythongiant** [comment]
Take a look at the docs for the preview Link - www.github.io 
we don't need screenshot of the code but ss of the result.

**Comment by Ashwanth7230** [comment]
where to check my result

**Comment by pythongiant** [comment]
dont you see the results before pushing them to the repo?. Please do proper testing before making a PR

**Comment by Ashwanth7230** [comment]
I had tested the same code by running it on my own  page can I keep the screen shot of that

**Comment by Ashwanth7230** [comment]
Link is:-

https://ashwanth7230.github.io/Fossasia-Page/

**Comment by Ashwanth7230** [comment]
Is it right?

**Comment by Ashwanth7230** [comment]
Kept screenshot check once

**Comment by Ashwanth7230** [comment]
Which one should i

**Comment by jakubpawlina** [comment]
The preview link should redirect to GitHub Page built for [this](https://github.com/Ashwanth7230/gci18.fossasia.org) repository. It'll look like `name.github.io/repo_name`.

**Comment by NishithP2004** [comment]
Check https://gci18.fossasia.org

**Comment by abishekvashok** [comment]
Clsoing as gitter already present.

**Pull request closed without merging**
