### PR TITLE
Added 404 Page

### LINKED ISSUE #209: 404 Page
**Actual Behaviour**

Currently, There is no 404 page 

**Expected Behaviour**

A website should ideally have a 404 page so that user could go back to the main page if required

**Would you like to work on the issue?**

Yes I am working on it.

### PR DESCRIPTION
**Pull request by Sid911**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link]( https://sid911.github.io/gci18/ )
- Fixes #209 
- Added Lottie to the project (More about lottie : https://github.com/airbnb/lottie-web/ )..

## Description / Changes
Added new 404 page to the website and also implemented lottie, which might help in later usecases

### Before:
image

### After:

image
- - - - - - - - - - - -

### CODE REVIEW

**Comment by Sid911** [comment]
@jogendra There is a address and its little button down below saying to go to the home page..... I will add line "You are on wrong page"

**Comment by Sid911** [comment]
@jogendra  Done Sir...

**Comment by jogendra** [comment]
User have to scroll the page to see button. this is not good practice. it should be visible without scrolling. Please fix it.

**Comment by Sid911** [comment]
@jogendra  should I keep it above the 404?

**Comment by jogendra** [comment]
Keep it just below the design.

**Comment by Sid911** [comment]
@Sid911  Is this much fine?
image

**Pull request merged**
