### PR TITLE
Fixes #49 , Fixes #29 : Added social icons to social section and footer

### LINKED ISSUE #29: Update the social media links in the footer section
Clicking on the social media icons take s to the top of the page. Need to be updated with proper link reference.

### LINKED ISSUE #49: Add more Social Media links to the Social Media Section
**Actual Behaviour**

Only Twitter and Facebook present

**Expected Behaviour**

All should be there

**Steps to reproduce it**

- Add the icons
- Add the links

**Screenshots of the issue**
screen shot 2018-10-26 at 8 53 27 pm

**Would you like to work on the issue?**

Yes, working on it.

### PR DESCRIPTION
**Pull request by saarthakchats**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes #49
- [Preview Link](https://saarthakchats.github.io/pppppp/)
-

## Description / Changes
- Added more Social Media Icons
- Added Icons and links to footer

### CODE REVIEW

**Comment by liveHarshit** [comment]
Do not mention fixes for #29 in the description, It will close this issue which is assigned to a task. Only mention for #47. You can mention both in last of your commit message.

**Comment by saarthakchats** [comment]
Okay

**Comment by saarthakchats** [comment]
Done @liveHarshit

**Comment by liveHarshit** [comment]
I think the last PR is for same issue #49, you have to wait.

**Comment by saarthakchats** [comment]
@liveHarshit 
That is for the footer

**Comment by saarthakchats** [comment]
If that one is merged, can I remove the footer code from mine and keep it limited to the social section

**Comment by liveHarshit** [comment]
It is for setting the target to blank.

**Comment by saarthakchats** [comment]
My PR is unrelated then, it has nothing to do with target to blank

**Comment by liveHarshit** [comment]
Change commit message to `Add social icons to social section and footer (#29)`

**Comment by saarthakchats** [comment]
@liveHarshit here

**Comment by saarthakchats** [comment]
@liveHarshit @abishekvashok 
Please merge.. i'll get conflicts again

**Pull request closed without merging**
