### PR TITLE
optimize images

### PR DESCRIPTION
**Pull request by ammarbinfaisal**
- [x] Included a Preview link
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://ammarbinfaisal.github.io/gci18.fossasia.org)

## Description / Changes

converted images form
- PastMemories
- mentors
- student
directories to webp and reduced the size of jpg/png ones if they were too large by using MozJPG encoder.
The images in mentors section are reduced to 10kb and less than that and those in PastMemories directory are reduced to <30kb. 

I don't think these issues regarding images need to be closed because much more optimization is possible. Theimages webps in the PastMEmories directry can be reduced more (useless we want to support this site on something like 50inch screen :laughing: 

I have also fixed the issue of students' images not loading after Rahl Arora and added myself to the students section

for #542 and #541 

- - - - - - - - - - - -

### CODE REVIEW

**Comment by Ryan10145** [comment]
@ammarbinfaisal Please only make one change per PR. Optimizing images, fixing the student section and adding yourself should all be done in separate PRs. Also, to fix the Travis build, please make sure that the images you added (ammar.jpg and ammar.webp) are the correct size (240x240).

**Comment by ammarbinfaisal** [comment]
I think just optimizing the images in a PR is fine even though it aims at tackling two different issues but very closely interrelated to each other

**Comment by Ryan10145** [comment]
@ammarbinfaisal Please resolve the merge conflicts.

**Comment by ammarbinfaisal** [comment]
@Masquerade0097 @nikit19 can u please have a look at this PR again

**Comment by ammarbinfaisal** [comment]
I have kept all images in students folder below 12kb and in projects folder 20kb(except spark.png because it has transparent pixels and mozjpeg doesn't seem to support them and optipng encoder also isn't reducing the size of the image). actually Ive used squoosh.app for images individually as I ddnt intend to spoil them
so I think a check for PRs adding images in students or projects folder would be fine. but I do need mentors to respond to this before I create an issue

**Comment by ammarbinfaisal** [comment]
i messed up everything due to my lack of knowledge of git.
sorry for that :disappointed: , I had to resolve conflicts and convert other images which were added to webp/jpg(mozjpeg) but sorry now I dont think I can do this - dont have much spare time due my school tests. Ironically, there isnt a proper response on this PR by any mentor so I think reducing the image sizes to half or more than that isnt something being taken seriously

**Pull request closed without merging**
