### PR TITLE
Added language translation

### PR DESCRIPTION
**Pull request by subhahu123**
Preview link After changes  ; https://subhahu123.github.io/foss/
preview link Before changes : https://gci18.fossasia.org/
# Changes done in this Pull Request

various language added using google translator
Preview link : https://subhahu123.github.io/foss/
Fixed  Issues : #191 

## Description / Changes
Adding google API in top layer of website by editing header.html
It provides variation of many language .with a single click we can change the language of entire website . 
This will be helpful for non-native english person .
So. he/she can also contribute too.

### CODE REVIEW

**Comment by subhahu123** [comment]
@sarnava1
@sk9331657
successful PR

**Comment by subhahu123** [comment]
@sarnava1
means of LGTM

**Comment by sarnava1** [comment]
**LGTM**-Looks Good To Me

**Comment by STEdirisuriya** [comment]
Google Translate Tool is not perfect for all the languages. We should use some JS method to translate the page.

**Comment by sk9331657** [comment]
@subhahu123  Why is the top navigation menu not showing up??

**Comment by subhahu123** [comment]
@sk9331657 
please send me the link

**Comment by sk9331657** [comment]
> @sk9331657
> please send me the link

 https://subhahu123.github.io/foss/

**Comment by subhahu123** [comment]
@sk9331657
it is working

**Comment by sk9331657** [comment]
> @sk9331657
> it is working
 See the navigation bar.
screenshot from 2018-11-08 23-37-21

**Comment by subhahu123** [comment]
@sk9331657
it's working for me 
screenshot from 2018-11-08 23-51-15

**Comment by liveHarshit** [comment]
Also, Nav bar taking double space after scrolling.

**Comment by subhahu123** [comment]
Ok i will do changes so that UI looks good

**Comment by subhahu123** [comment]
@sarnava1
http://subhahu.me/
working on ...........

**Comment by subhahu123** [comment]
preview link : subhahu.me
done
finally
@sarnava1
@sk9331657
@mariobehling @tabesin
@liveHarshit

**Comment by subhahu123** [comment]
review the new changes

**Comment by subhahu123** [comment]
double spaces ??????
navbar color ???????????
please explain with screenshot

**Comment by subhahu123** [comment]
#335

**Pull request closed without merging**
