### PR TITLE
Make Memories Section Responsive

### LINKED ISSUE #281: Make memories section responsive
**Actual Behaviour**

 memories section added isnt resposive. The image added should reduce in number on screens with less width. shrunken images look weird.

**Steps to reproduce it**
go to the [original website](https://gci18.fossasia.org)

**Would you like to work on the issue?**
Open to all

### PR DESCRIPTION
**Pull request by KSNINJA**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://ksninja.github.io/gci18.fossasia.org/)

- Fixes #281 

## Description / Changes
Made Fossasia Album section responsive to different screen sizes .

### After:
screenshot 2018-11-11 at 5 49 59 pm
screenshot

- - - - - - - - - - - -

### CODE REVIEW

**Comment by abishekvashok** [comment]
Yes

**Comment by KSNINJA** [comment]
@abishekvashok Please review my task now

**Comment by jogendra** [comment]
@KSNINJA Please resolve the conflicts

**Comment by KSNINJA** [comment]
Now, I have used Bootstrap to make the Fossasia Album Sectoin responsive .

**Pull request merged**
