### PR TITLE
changed the projects cards

### PR DESCRIPTION
**Pull request by Sid911**
# Changes done in this Pull Request

-Made changes to cards of project section
- Preview link = https://sid911.github.io/gci18/students_projects.html
## Description / Changes
Used UI kit for doing so
- Added Parallax effect
- Added responsive Card grid

### After:
image

Working on adding background
### Before:
image

### CODE REVIEW

**Comment by Sid911** [comment]
Can anyone put a wip tag

**Comment by fragm3** [comment]
@Sid911 added WIP tag

**Comment by simarsingh24** [comment]
add wip in PR description too!

**Comment by fragm3** [comment]
@Sid911 please resolve conflicts, 2 hours left for contest to end.

**Comment by sk9331657** [comment]
@Sid Update the PR.

**Comment by Sid911** [comment]
I am out of station, that's why I am away from computer... I will just close this and make a new one when I am back, I will notify maintainers through gitter.

**Pull request closed without merging**
