### PR TITLE
Added new mentor (GCI)

### LINKED ISSUE #96: Some mentors are missing from the Mentors section
**Actual Behaviour**
* Some mentors are missing from the Mentors section

**Expected Behaviour**
* All mentors should be present in the PR

List of mentors - 
- [x] Shubham Kumar
- [x] Harshit Khandelwal
- [x] tabesin
- [x] Shashank Kumar
- [x] Saurabh Srivastava 
- [x] Akshat Garg
- [x] Arundhati Gupta
- [x] Jogendra Singh
- [x] Anshuman Verma
- [x] Sanskar Jethi
- [x] Akshat Jain
- [x] Mohit Sharma
- [x] Prateek Chanda
- [x] Mohit Kumar
- [ ] Hon Nguyen
- [x] Abishek V Ashok
- [x] Rohit Potter
- [x] Shubham Gupta
- [x] Nikit Bhandari
- [ ] Tarun Kumar
- [x] Sridhar Jajoo 
- [ ] Simranpreet kaur

Note - Please add 1 mentor per PR so that all the students get a chance to work on it.

### PR DESCRIPTION
**Pull request by Sid911**
-Added new mentor Sumedhe Dissanayake in the mentor section 
-fixes #96 
-Github Pages : https://sid911.github.io/gci18/

### CODE REVIEW

**Comment by Sid911** [comment]
@jogendra Thank you for informing #stillLearning😊

**Comment by rpotter12** [comment]
@Sid911 please resolve conflicts. So that we can merge this

**Comment by sk9331657** [comment]
@Sid911  Resolve Conflicts.

**Comment by Sid911** [comment]
Done sir..😊

**Comment by Sid911** [comment]
@akshatnitd  Is it fine now?....

**Comment by Sid911** [comment]
Hong Phuc Dang, Harshit Prasad... anyone of these are on the list?

**Comment by akshatnitd** [comment]
The list is present on the issue description - https://github.com/fossasia/gci18.fossasia.org/issues/96

**Comment by Sid911** [comment]
AT last done... I hope so😊💻

**Comment by Sid911** [comment]
I will get that done.... 😊

**Pull request closed without merging**
