### PR TITLE
Added a student project to GCI Fossasia site.

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link]Https://nishithp2004.github.io/gci18.fossasia.org

- Fixes #<Issue Number>

## Description / Changes
Hi I have add my personal portfolio to the students project section.

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by NishithP2004** [comment]
@sarnava1 Sorry the page building has failed as there is already a page with name gci18.fossasia.org

**Comment by NishithP2004** [comment]
@fragm3 I have removed the extra lines as requested.

**Comment by jakubpawlina** [comment]
@NishithP2004 Please squash the commits yet

**Comment by NishithP2004** [comment]
@jakubpawila At this point I am not able not squash my last 5 commits.

**Comment by NishithP2004** [comment]
@jakubpawlina

**Comment by jakubpawlina** [comment]
Ok, I see. It seems to be ready

**Pull request merged**
