### PR TITLE
[Fixed #326] Added students project page again and improved it.

### LINKED ISSUE #326: Student projects section is not found.
**Actual Behaviour**
The projects page is not found. There was a students project section, https://github.com/fossasia/gci18.fossasia.org/pull/189/files; But however it has deleted.
image

**Expected Behaviour**

Add it again completely new and improve it. 

**Would you like to work on the issue?**

Yes. I'm working

### PR DESCRIPTION
**Pull request by STEdirisuriya**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request
I think to leave two commits because I did two things. 
From the first commit, I added students' project section which was already there.
From the second commit, I improved it and add one of my projects,

Preview link - https://stedirisuriya.github.io/gci18.fossasia.org
Preview link for students projects page - https://stedirisuriya.github.io/gci18.fossasia.org/students_projects.html
Issue - #326 

Thank you!

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
@sk9331657 It's because it using Jekyll template. The header is it made to index.html with default layout same header came into this also. I think it was already, am I need to change it?

**Comment by STEdirisuriya** [comment]
@nikit19 OK, but I didn't think these two commits should make in two PRs because in first I added the page was earlier and in the second I renamed it to another name. So it's also like deletion I don't think a file which is to be deleted need another PR.

**Comment by STEdirisuriya** [comment]
@sk9331657 I added a new layout and include (header), Now it's fine we can use this new layout for other pages without index.html

**Comment by fragm3** [comment]
Merging this, changes in nav bar can be done in subsequent PR.

**Comment by liveHarshit** [comment]
Task link: https://codein.withgoogle.com/dashboard/task-instances/6053266837209088/

**Comment by STEdirisuriya** [comment]
@liveHarshit Thank you!

**Pull request merged**
