### PR TITLE
Hotfix: YouTube API in the video section (#547)

### LINKED ISSUE #547: Fix the Jekyll loop for YouTube API
**Actual Behaviour**
YouTube API has recently been added to the videos section, but due to how jekyll makes it's loops inside a js script the section breaks with multiples video added.

**Expected Behaviour**
The section should allow multiple videos.

**Steps to reproduce it**
Fork the repo and try adding more videos to the videos.yml file.

**Screenshots of the issue**
image

**Would you like to work on the issue?**
Yes, a hotfix is almost ready.

### PR DESCRIPTION
**Pull request by AppleC4T**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://applec4t.github.io/gci18.fossasia.org/)

- Fixes #547 

## Description / Changes
While locally testing the recently added script in the video section I noticed that when adding more videos the loop brakes and the videos don't display. This is a quick hotfix to ensure that more videos can be added in the future.
Main changes:
- fixed the jekyll bug, ensuring that the section can handle multiple videos
- changed the alignment of videos (the videos now align like the mentors/students cards in order to achieve responsibility)

### Before:
Trying to add more videos:
image
### After:
Current section with one video:
screenshot_2
Example of multiple videos:
screenshot_1

- - - - - - - - - - - -

### CODE REVIEW

**Comment by sarnava1** [comment]
@abishekvashok I guess with more videos it will look better. 4 videos in a row and so it will be better without centering them.

**Comment by AppleC4T** [comment]
@abishekvashok @isuruAb I tried center aligning the videos few times, but then the iframes wrap around wrong and get too big. So I think we should go with the mentor-card alignment if we want to keep a clean look and responsiveness.
image

**Comment by AppleC4T** [comment]
Done!

**Comment by AppleC4T** [comment]
@jakubpawlina can you tell me something more about your environment or how to recreate this bug. Because on your screenshot the video is aligned to the left while it should be centered. Of course, I'll fix the text nonetheless but I'm just curious how you got that to happen.

**Comment by jakubpawlina** [comment]
@AppleC4T I suppose, I don't use very peculiar environment. I was testing the website in Google Chrome v 70.0.3538.110 (Official) (64-bit). I tried changing the window size to see what happenes and  this accident on website occured. I attach one more screenshot with opened developer console, so that it could be easier to find the bug. I haven't found it yet but I'll add a description of reason if I had.
zrzut ekranu 131

**Comment by AppleC4T** [comment]
@jakubpawlina I've found it. It's not a bug it's just how bootstrap handles the alignments. From what I've found it only occurs when you dock your console to the side and start scaling the window, so it shouldn't happen for any standard user.

**Comment by jakubpawlina** [comment]
@AppleC4T ok, so it should stay as is

**Comment by poush** [comment]
Though one think, IDs of elements are directly used as video IDs. I would suggest adding some prefix. You can create separate issue for this.

**Pull request merged**
