### PR TITLE
Added Nepali Translation.

### PR DESCRIPTION
**Pull request by Jeewal**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
The Preview link is : https://jeewal.github.io/gci18.fossasia.org/

## Description / Changes
Added Nepali Translation of Thank You for your Contributions in Thankyou.js

### CODE REVIEW

**Comment by liveHarshit** [comment]
Which issue does it relate?

**Comment by Jeewal** [comment]
Isn't related to any issue i guess !

**Comment by abishekvashok** [comment]
> Which issue does it relate?

It's a GCI task.

**Comment by abishekvashok** [comment]
Task link: https://codein.withgoogle.com/dashboard/task-instances/6227026517164032/

**Pull request merged**
