### PR TITLE
Add Team Section  Issue #251

### PR DESCRIPTION
**Pull request by KSNINJA**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
1.  Add Fossasia's Team section . 
2. Formatted Student's Section.
3. Rearranged different sections .

See Issue https://github.com/fossasia/gci18.fossasia.org/issues/251

- [Preview Link](https://ksninja.github.io/gci18.fossasia.org/)

### CODE REVIEW

**Comment by sk9331657** [comment]
@mariobehling  Do we require TEAM Section for the website since we already have mentor section?

**Comment by KSNINJA** [comment]
The team section includes Fossasia members which have higher precedence than mentors  like event managers , infrastructure , design , which we cannot include in mentors

**Comment by STEdirisuriya** [comment]
What is the related issue?

**Comment by KSNINJA** [comment]
See Issue #251

**Comment by KSNINJA** [comment]
Please confirm . Also , I have a suggestion of having a section having photos from Fossasia Events . If the Team Section is invalid , can I work on this ?

**Comment by STEdirisuriya** [comment]
@KSNINJA Mention the resolved issue in your PR title.

**Comment by liveHarshit** [comment]
Task link: https://codein.withgoogle.com/dashboard/task-instances/5986491571372032/

**Pull request merged**
