### PR TITLE
Added me as student

### PR DESCRIPTION
**Pull request by Ashwanth7230**

### CODE REVIEW

**Comment by Ashwanth7230** [comment]
https://github.com/Ashwanth7230/gci18.fossasia.org/tree/master/img/students

**Comment by sk9331657** [comment]
> https://github.com/Ashwanth7230/gci18.fossasia.org/tree/master/img/students

Preview link.

**Comment by STEdirisuriya** [comment]
Provide a description for all the PRs.

**Comment by sk9331657** [comment]
@Ashwanth7230  Update the PR.

**Comment by prateekiiest** [comment]
Any updates on this?

**Comment by fragm3** [comment]
Closing this PR, due to inactivity. Please create a new PR with appropriate changes.

**Pull request closed without merging**
