### PR TITLE
Add language translator

### LINKED ISSUE #400: Add language translator
# Issue
The language selector in the navigation bar doesn't work . 
We need to add a language translator to the website .

**Would you like to work on the issue?**
Yes , I would like to work on the issue .

### PR DESCRIPTION
**Pull request by KSNINJA**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://ksninja.github.io/gci18.fossasia.org/)

- Fixes #400 

## Description / Changes
Added Google translate to the website . Now , we can view the website in 5 major languages -
Chinese , French , Hindi , English , Japanese and Spanish . 
Resized images in Team section.

### After:
The following is in French 
image

- - - - - - - - - - - -

### CODE REVIEW

**Comment by KSNINJA** [comment]
Please confirm if the issue can be considered advanced .

**Comment by KSNINJA** [comment]
@saarthakchats  I tried to override the styles of that dropdown menu . But that css was not being shown in the element styles when I tried using Web Inspector

**Comment by KSNINJA** [comment]
Earlier I added all the languages . And the languages showed as a grid , which is not responsive to mobiles . So , I had to remove it . I was not even able to override those styles . @STEdirisuriya

**Comment by Ryan10145** [comment]
@KSNINJA There are some aspects of the website that shouldn't be translated, as Google translate doesn't do a good job and certain components of the website lose meaning. This is most obvious with the names of mentors/students, which get translated into meaningless things.

image

I think it would be better to blacklist those from the translation and just keep the original text.

The "Thank you for Contributing!" section should also be blacklisted, as the purpose of that section is to have multiple languages, but then some of them just get translated.

Also, I get severe lag once I translate and begin scrolling, which is an issue. The scrolling becomes very choppy.

**Comment by sahilsaha7773** [comment]
@Ryan10145 I too agree with you

**Comment by fragm3** [comment]
Closing this, as https://github.com/fossasia/gci18.fossasia.org/pull/412 has been merged. Not required any more.

**Pull request closed without merging**
