### PR TITLE
Compressed and Merged Files to reduce network request

### LINKED ISSUE #476: Too many requests and slow website.
**Actual Behaviour**

It's should be load faster with less request

**Expected Behaviour**

Too many requests and slow website.

**Steps to reproduce it**
https://gci18.fossasia.org/

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by niteshkumarniranjan**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://niteshkumarniranjan.github.io/gci18.fossasia.org/)

- Fixes #476 

## Description / Changes
Formatted Code
Compressed all images
Merged CSS files
Added CDN for faster load
Merged multiple inline scripts into one inline scripts.

From 507 to 485 requests
From 16MB to 14MB

### Before:

screenshot from 2018-11-24 20-09-29

### After:
screenshot from 2018-11-24 20-09-16

- - - - - - - - - - - -

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
Squash your commits

**Comment by niteshkumarniranjan** [comment]
@STEdirisuriya I have left it on purpose so that it's clear about my changes.

**Comment by abishekvashok** [comment]
Awesome! Thanks

**Comment by niteshkumarniranjan** [comment]
👍

**Pull request merged**
