### PR TITLE
Added smooth scrolling effect Fixes #152

### LINKED ISSUE #152: Add smooth scrolling to navbar links
**Actual Behaviour**

Links in the navbar snappily take us to the section on the page

**Expected Behaviour**

It should scroll smoothly

**Steps to reproduce it**

Add the required code

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Sid911**
# Changes done in this Pull Request

- Github Pages Preview Link : https://sid911.github.io/gci18/
- Fixes #152 
-Added a native scrolling effect for moving in sections

## Description / Changes
Removed the snappy movement of moving to sections....

### CODE REVIEW

**Comment by Sid911** [comment]
@sarnava1 should I decrease the speed? if the site gets longer it would take a lot more time....

**Comment by Sid911** [comment]
I am trying to find the right spot... The native library slingshots the transition depending on how far is the destination, so if the things are near then the animation might seem a bit too slow
🚀😊

**Comment by Sid911** [comment]
@sarnava1 can't really find a way to change to speed of transition.... I looked up but No luck

**Comment by sarnava1** [comment]
@Sid911 No problem. It was only a suggestion. Keep up the good work.

**Pull request merged**
