### PR TITLE
Improve Loading times (#429)

### LINKED ISSUE #429: High load times and very high cpu usage
**Actual Behaviour**

Right now the website Is having many elements which are being  parsed and processing while the page loads, which in turn gives very large load times and system usage
**Expected Behaviour**

The website should be fast To load and should lazy load the sections once the user scrolls down, this will cut down the initial usage and spread out evenly when the user scrolls down.

**Proposal**
Adding a lazy loading system to the website

**Would you like to work on the issue?**

anyone can work on it

### PR DESCRIPTION
**Pull request by KSNINJA**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://ksninja.github.io/temp/)

- Fixes #429 

## Description / Changes
Added lazy loading for images and map . Changed extension of images from png to jpg , which provides better compression .  

### Before:
image

### After:
image

- - - - - - - - - - - -

### CODE REVIEW

**Comment by simarsingh24** [comment]
@KSNINJA please add WIP resolve conflicts and follow commits guidelines

**Comment by KSNINJA** [comment]
Work done . Please review now .

**Comment by ammarbinfaisal** [comment]
It is being used in my PR. So if we need webp then it would be better if
that gets merged first. i am just going to fix the branch conflicts

**Comment by jogendra** [comment]
@abishekvashok `webp` sometimes doesn't render well in Safari

**Comment by KSNINJA** [comment]
@jogendra They don't render at all . Webp is specifically for chrome

**Comment by ammarbinfaisal** [comment]
@jogendra we arent switching to webp completely. jpgs and pngs are there for backup.
and I am extremely sorry for the delay on my part but I think some work in projects/students directories is required due to some negligence on my part earlier

**Comment by Sid911** [comment]
I added a fallback system to the webp's that I initially added, so it changed to jpg if necessary. You could just convert them to webp's and then keep jpg's as secondary.

**Comment by KSNINJA** [comment]
> I added a fallback system to the webp's that I initially added, so it changed to jpg if necessary. You could just convert them to webp's and then keep jpg's as secondary.

Yes, that's the only solution . @ammarbinfaisal is working on it . 
In gci18.fossasia.org , the only optimisation left is images . But we also need to maintain the image quality . So , pls don't try to compress images more . Try to use webp only and jpg as secondary .

**Comment by Sid911** [comment]
> @jogendra They don't render at all . Webp is specifically for chrome

and edge

**Pull request merged**
