### PR TITLE
Student data added

### PR DESCRIPTION
**Pull request by arihantbansal**
* Added student image

* Added student data

- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://arihantbansal.github.io/fossasiagci18/) 

- Fixes #<Issue Number>

## Description / Changes
Added the student data and image as per the GCI task.

### Before:
old

### After:
new

- - - - - - - - - - - -
 [preview link url]: https://arihantbansal.github.io/fossasiagci18/

### CODE REVIEW

**Comment by arihantbansal** [comment]
Changed dimensions

**Comment by Ryan10145** [comment]
@arihantbansal Please fix the preview link as it currently is not working. Also, make sure you squash your commits.

**Comment by rpotter12** [comment]
@arihantbansal always try to do one work in 1 PR. You should add mentor and student profile in separate PR :)

**Comment by arihantbansal** [comment]
Updated preview link. Please merge.

**Comment by arihantbansal** [comment]
Pulled latest codebase

**Comment by arihantbansal** [comment]
I don't know why top links aren't working. I didn't touch any of that code.

**Pull request closed without merging**
