### PR TITLE
Removed PHP files

### PR DESCRIPTION
**Pull request by niteshkumarniranjan**
Fixes : https://github.com/fossasia/gci18.fossasia.org/issues/23

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
Just create a issue saying site has unwanted php files and mention it in the pr.

**Comment by niteshkumarniranjan** [comment]
Deleting PHP files doesn't need a preview in websute,

**Comment by YashKumarVerma** [comment]
Just to check if nothing has broke, it's always good to add a preview link.

**Comment by niteshkumarniranjan** [comment]
My fault sorry! : https://niteshkumarniranjan.github.io/gci18.fossasia.org/

**Comment by ms10398** [comment]
> Deleting PHP files don't need a preview in website,

Yes it doesn't need a preview link but every PR should have a preview link attached to keep it a consistent practice and maybe soon we would have an issue and PR template to keep it consistent

**Comment by sarnava1** [comment]
@niteshkumarniranjan your link gives 404 error. Please check.

**Comment by niteshkumarniranjan** [comment]
Its giving me CNAME error?

**Comment by niteshkumarniranjan** [comment]
screenshot from 2018-10-24 22-32-50

**Comment by ms10398** [comment]
The site deployment takes time and it is deployed now!

It works flawlessly as it should :slightly_smiling_face: 

Thanks @niteshkumarniranjan

**Comment by niteshkumarniranjan** [comment]
Thanks everyone Now Please merge this So that I can move on to next Issue.

**Pull request merged**
