### PR TITLE
[Review Required] Added geolocation of all the mentors 

### LINKED ISSUE #643: add the mentors location in the map
**Actual Behaviour**

currently only few mentors location are there on the map.

**Expected Behaviour**

the location of all the mentors should be added to the map. :)

List of Mentors
* [ ] Jogendra | Kumar
* [ ] Wei Tat | Chung
* [ ] Shubham | Gupta
* [ ] Shubham | Kumar
* [ ] Soong Chee | Gi
* [ ] Akshat | Garg
* [ ] Abhijeet Singh | Khangarot
* [ ] Tarun | Kumar
* [ ] Abishek | V Ashok
* [ ] SARNAVA | KONAR
* [ ] Eden | D
* [ ] Harshit | Khandelwal
* [ ] Hong Phuc | Dang
* [ ] Akshat | Jain
* [ ] simranpreet | kaur
* [x] ROHIT | POTTER
* [ ] Nikit | Bhandari
* [ ] Priyanshu | Khandelwal
* [ ] André | Rebentisch
* [ ] Sanskar | Jethi
* [ ] Anshuman | Verma
* [ ] Mayank | Vaidya
* [ ] THIYAGARAJ | T
* [ ] Prateek | Chanda
* [ ] Shubham | Kumar Singh
* [ ] Arundhati | Gupta
* [ ] Chashmeet | Singh
* [ ] Madhushanka | Padmal
* [ ] Abhinav | Raj
* [ ] Praveen | Ojha
* [ ] Harsh | Patel
* [ ] Anup | Panwar
* [ ] Praduman | Singh
* [ ] Sridhar | Jajoo
* [ ] Mohit | Sharma
* [ ] Suneet | Srivastava
* [ ] Dilpreet | Singh
* [ ] Rupav | Jain
* [ ] Pranjal | Paliwal

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://nishithp2004.github.io/gci18.fossasia.org)

- Fixes #643 

## Description / Changes
Hi I have successfully added the location of all the mentors 

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by NishithP2004** [comment]
@pranav1698 But isn’t it good if we keep all the code other than css ready, so that when the site is up again it will have all the necessary features.

**Comment by NishithP2004** [comment]
@rpotter12 Please merge it

**Comment by rpotter12** [comment]
@NishithP2004 wait for 2nd approval. We have to merge PR which is having 2 or more than 2 approval. :)

**Comment by NishithP2004** [comment]
> @NishithP2004 wait for 2nd approval. We have to merge PR which is having 2 or more than 2 approval. :)

Sorry was not aware of that

**Pull request merged**
