### PR TITLE
Adding link for already registered users

### PR DESCRIPTION
**Pull request by PAPERPANKS**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Added a link to the login page under registration form
- Preview Link
  - Post commit view
  gciupdated

  - Before commit view
  47556560-45f0d680-d92c-11e8-9344-1dfa9976947e

## Description / Changes
- A navigation link to the login page is added for the already registered users.
- A separator line `<hr/>` is also added to distinguish both paragraphs.
- Adding style for `<hr/>` in `css/custom.css`

### CODE REVIEW

**Comment by PAPERPANKS** [comment]
@fragm3  Done here is the link https://ipu-master.000webhostapp.com/page-register.html

**Comment by fragm3** [comment]
@PAPERPANKS squash your commits into one. You can see: https://davidwalsh.name/squash-commits-git

**Comment by realslimshanky** [comment]
@fragm3 no need to ask the contributor to squash commits. As a maintainer, we have that option right from this very page to squash before merging. Only check for the issues with the code.

**Comment by fragm3** [comment]
@realslimshanky Okay

**Pull request merged**
