### PR TITLE
(#236)(#258)Enabled Travis Checks For Image Dimensions

### LINKED ISSUE #236: Add Travis Checks for image dimensions
Ping @abishekvashok 
Should I attempt to do it using https://github.com/abishekvashok/img_checker 
Will this be an advanced issue?

### LINKED ISSUE #258: Images Out of Dimentions
**Actual Behaviour**
```
The image ./img/mentors/mentor.jpg is larger than 240px x 240px [w x h]
The image ./img/mentors/YKV.jpg is larger than 240px x 240px [w x h]
The image ./img/mentors/akshatnitd.jpg is larger than 240px x 240px [w x h]
The image ./img/projects/niteshkumarniranjan.png is larger than 240px x 500px [w x h]
The image ./img/projects/Tick..png is larger than 240px x 500px [w x h]
The image ./img/projects/spark.png is larger than 240px x 500px [w x h]
The image ./img/students/sr.png is larger than 240px x 240px [w x h]
The image ./img/students/hzimny.jpg is larger than 240px x 240px [w x h]
Image Checker: These images exceeds the specified dimensions
8 image(s) have greater dimensions then specified.
```

**Expected Behaviour**
- All Project Images should be 240x500
- All other images should be 240x240

**Steps to reproduce it**

Change the dimensions

**LogCat for the issue**

**Screenshots of the issue**

screenshot 2018-11-06 at 10 52 41 pm

**Would you like to work on the issue?**
Yes, others can claim and work also

### PR DESCRIPTION
**Pull request by saarthakchats**
- [ ] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Fixes #236 
- Fixes #258 

## Description / Changes
- Added checks to ensure images are 240x240
- Added check to ensure Project Images are 500x240
- Resized all requires images

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by saarthakchats** [comment]
#258

**Comment by STEdirisuriya** [comment]
@saarthakchats  I think you could resize not suitable images as you mentioned dimensions.

**Comment by saarthakchats** [comment]
@STEdirisuriya That is a very different thing from actually adding the checks
So I'll make another PR for it, or create an open issue for that matter

**Comment by abishekvashok** [comment]
> @saarthakchats you can use that, it would be an advanced issue, I reckon, if you could apply the tests and fix the failing ones as well.

**Comment by saarthakchats** [comment]
@abishekvashok Okay, I'll do them

**Comment by saarthakchats** [comment]
The checks have passed now!

**Comment by STEdirisuriya** [comment]
@saarthakchats LGTM!

**Comment by saarthakchats** [comment]
@abishekvashok @mariobehling 
Please merge and enable :D

**Comment by abishekvashok** [comment]
Thanks for this :)

**Comment by saarthakchats** [comment]
👍 @abishekvashok

**Pull request merged**
