### PR TITLE
[Issue - #496 | point 2] Compressed images and increase load time

### LINKED ISSUE #496: Remove unwanted files and compress images.
**Actual Behaviour**

There are a lot of files unwanted and useless. (Images, Videos, HTML theme files...) 
A lot of images need to compress. 

**Expected Behaviour**

Remove unwanted and unused files, decrease the size of repo to maintain a perfect repository. #188 
Compress all the images.

**Would you like to work on the issue?**

Yes of course!

### PR DESCRIPTION
**Pull request by STEdirisuriya**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://STEdirisuriya.github.io/gci18.fossasia.org)
- Fixes #496 point 2
- Compressed images.

### Thank you!

### CODE REVIEW

**Comment by pythongiant** [comment]
decreasing the size reduces the load time how?

**Comment by STEdirisuriya** [comment]
When there are a lot of files, it needs to open all. Decreasing the size will improve the speed.

**Comment by rpotter12** [comment]
@STEdirisuriya I think you are right.

**Comment by STEdirisuriya** [comment]
@sid911 They can use documentation in either bootstrap or template of this site. When new developers have to clone this, it will take more data usage and time too. So deleting unnecessary files will help to decrease the size of the repo as well. You could see the difference below,
image
Link - https://www.dareboost.com/en/comparison/d_5bfa6cc3e9679034178c6557/d_5bfa6cc4e9679034178c655a/

**Comment by STEdirisuriya** [comment]
@Sid911 Deleting unnecessary files will help new developers to download files quickly. If they need some help I think they can refer documentations in Bootstrap and related template. Also, I think it will increase the time of loading.

**Comment by STEdirisuriya** [comment]
image
image

image
image

**Comment by Sid911** [comment]
Don't show that page... lighthouse is not consistent, as it is still in beta testings that is the reason I only show the real performance test in web tools... And as I tested, (images below)..... plus bootstrap is not our main css file... it's the custom `theme-red.css file` and there is no documentation about it anywhere other than those files... That is also the reason I left those when I deleted the rest of the files... and it really helps when at least I don't know how to do **something**.

image
image

**Comment by STEdirisuriya** [comment]
Waiting for other mentors to review it.

**Comment by Sid911** [comment]
Yep.... just post in gitter @STEdirisuriya

**Comment by abishekvashok** [comment]
You don't reduce loading time of a website by deleting files not imported to it (unused files)

**Comment by abishekvashok** [comment]
You could reduce the repo size between

**Comment by STEdirisuriya** [comment]
@abishekvashok I'll doing some changes more than this, Please give me the time.

**Comment by STEdirisuriya** [comment]
@abishekvashok @pythongiant @Sid911 Could you please check now, I have compressed all the images files also more than deleting unnecessary files. I think it will definitely speed up the site.

**Comment by STEdirisuriya** [comment]
@Ryan10145 I have compressed the images. Compressing images will decrease the size and speed up the loading.

**Comment by Ryan10145** [comment]
@STEdirisuriya I agree in that the new changes should speed up the website a bit; I was just pointing out that if we wanted to measure the speed increase, we might need to use a different test.

**Comment by abishekvashok** [comment]
Can you limit the changes to those files then @STEdirisuriya, also consider adding a sperate issue for it.

**Comment by saarthakchats** [comment]
Arent you actually decreasing load time 😅

**Comment by STEdirisuriya** [comment]
@saarthakchats why you're telling like that?

**Comment by STEdirisuriya** [comment]
@abishekvashok I have done changes. Could you please check it now?

**Comment by abishekvashok** [comment]
Again the diff is so large. Consider copying the compressed images and videos to another file outside the repo, reset the commits made to your branch, update your branch with the main repo, and place them back. Then force push.

**Comment by STEdirisuriya** [comment]
@abishekvashok @Sid911 @saarthakchats @Ryan10145 @rpotter12 @pythongiant 
I have changed my issue description, I am going to remove unwanted files separately to decrease the size of the repo. 
https://github.com/fossasia/gci18.fossasia.org/issues/496
https://github.com/fossasia/gci18.fossasia.org/issues/188

From this PR I compressed images to speed up the site. 
 
Could you please review this now?

**Pull request merged**
