### PR TITLE
thank you in punjabi

### PR DESCRIPTION
**Pull request by gaurang7goel**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://gaurang7goel.github.io/gci18.fossasia.org/.)

- Fixes https://github.com/fossasia/gci18.fossasia.org/issues/374

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by gaurang7goel** [comment]
sir , sorry i was not able to do it.
pls tell how to do and give preview

**Comment by sk9331657** [comment]
> sir , sorry i was not able to do it.
> pls tell how to do and give preview

Search for hosting github repo on  github pages .

**Comment by gaurang7goel** [comment]
https://gaurang7goel.github.io/gci18.fossasia.org/.

**Comment by gaurang7goel** [comment]
thank you sir

**Comment by sk9331657** [comment]
> https://gaurang7goel.github.io/gci18.fossasia.org/.

Nice just add this link to pull request template of this pr.Also add issue your are solving.

**Comment by gaurang7goel** [comment]
its done ols check the link

**Comment by gaurang7goel** [comment]
sir actually i was doing it as a paret of GOOGLE CODE in task

**Comment by gaurang7goel** [comment]
thank you sir

**Pull request merged**
