### PR TITLE
link navbar to fossasia/gci pages and add social section

### LINKED ISSUE #41: link navbar to fossasia/gci pages and add social section
**Actual Behaviour**

navbar links to a discrete page

**Expected Behaviour**

navbar should link to related section/page

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by Ploypiti**
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Fixes #41 
- https://ploypiti.github.io/gci18.fossasia.org/

## Description / Changes
- made navbar navigates to fossasia/gci pages and social links

### CODE REVIEW

**Comment by liveHarshit** [comment]
Also add GCI icon

**Comment by Ploypiti** [comment]
@liveHarshit There's a GCI dropdown section already.

**Comment by liveHarshit** [comment]
> @liveHarshit There's a GCI dropdown section already.

I think there is no dropdown section for GCI pages

**Comment by Ploypiti** [comment]
@liveHarshit 

image
the `GCI` li also links to `https://codein.withgoogle.com/organizations/fossasia/` for that matter.

**Comment by liveHarshit** [comment]
Add icon like that

image

**Pull request merged**
