### PR TITLE
Added a better introductory section

### PR DESCRIPTION
**Pull request by Sid911**
# Changes done in this Pull Request

- Github Page: https://sid911.github.io/gci18/
-Deleted a template(Placeholder) section

###  Before and after 
1.
image
The Site directly starts with students

1.2.
image
The Site has an introduction section for new people.

### CODE REVIEW

**Comment by liveHarshit** [comment]
Why again and aganin social media section?

image
image
image
image

**Comment by Sid911** [comment]
@liveHarshit  I have deleted the the social section, Can this be merged for introduction section? 😊

**Comment by liveHarshit** [comment]
> @liveHarshit I have deleted the the social section, Can this be merged for introduction section?

Open explore fossasia URL in new tab.

**Comment by liveHarshit** [comment]
Also overlapping with students section. Fix it.

**Comment by Sid911** [comment]
working on it 😊

**Comment by Sid911** [comment]
@liveHarshit can you please check if the

**Comment by prateekiiest** [comment]
Good work @Sid911

**Pull request merged**
