### PR TITLE
Added Hong Phuc Dang as mentor

### LINKED ISSUE #96: Some mentors are missing from the Mentors section
**Actual Behaviour**
* Some mentors are missing from the Mentors section

**Expected Behaviour**
* All mentors should be present in the PR

List of mentors - 
- [x] Shubham Kumar
- [x] Harshit Khandelwal
- [x] tabesin
- [x] Shashank Kumar
- [x] Saurabh Srivastava 
- [x] Akshat Garg
- [x] Arundhati Gupta
- [x] Jogendra Singh
- [x] Anshuman Verma
- [x] Sanskar Jethi
- [x] Akshat Jain
- [x] Mohit Sharma
- [x] Prateek Chanda
- [x] Mohit Kumar
- [ ] Hon Nguyen
- [x] Abishek V Ashok
- [x] Rohit Potter
- [x] Shubham Gupta
- [x] Nikit Bhandari
- [ ] Tarun Kumar
- [x] Sridhar Jajoo 
- [ ] Simranpreet kaur

Note - Please add 1 mentor per PR so that all the students get a chance to work on it.

### PR DESCRIPTION
**Pull request by Sid911**
Added hong Phuc Dang in mentors section
-fixes #96
-Github Pages : https://sid911.github.io/gci18/

### CODE REVIEW

**Comment by jogendra** [comment]
@Sid911 I can't see added mentor in your given preview link

**Comment by Sid911** [comment]
@YashKumarVerma I don't know why, but All these days I tried to squash commits, I would always end up with some kind of error. So my alternative would be to just copy the things that I changed then delete before commits. 

I will try to do it from next time😊💻

**Comment by Sid911** [comment]
@YashKumarVerma  how can I squash the merge? I can't find a way.

**Comment by jogendra** [comment]
@Sid911 For squashing the merge commits, you have to `rebase` your branch with upstream.

**Pull request merged**
