### PR TITLE
Removed slack

### LINKED ISSUE #598: Take out Slack and add Gitter link to https://gitter.im/fossasia/fossasia instead
We are hardly using Slack these days. Please take it out and add the Gitter chat instead: https://gitter.im/fossasia/fossasia

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview link]https://nishithp2004.github.io/gci18.fossasia.org

- Fixes #598 

## Description / Changes
Hi I have replaced Slack with Gitter

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by NishithP2004** [comment]
@abishekvashok I have made the changes, please review.

**Comment by NishithP2004** [comment]
The preview link is updated as well.

**Comment by NishithP2004** [comment]
@abishekvashok

**Comment by NishithP2004** [comment]
@jogendra Where can I find the code file for the footer.

**Comment by jogendra** [comment]
@NishithP2004 Here 
        gci18.fossasia.org/_includes/footer.html

**Comment by NishithP2004** [comment]
@jogendra @abishekvashok I have removed it successfully.

**Comment by NishithP2004** [comment]
Please review

**Comment by jogendra** [comment]
@NishithP2004 please submit the task

**Pull request merged**
