### PR TITLE
Added Student Projects Page

### PR DESCRIPTION
**Pull request by niteshkumarniranjan**
Fixes https://github.com/fossasia/gci18.fossasia.org/issues/16
and
https://github.com/fossasia/gci18.fossasia.org/issues/10
screenshot from 2018-10-24 18-31-17

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
Preview link?

**Comment by niteshkumarniranjan** [comment]
Oops! I forgot the link :open_mouth: 
Here's the preview link: https://niteshkumarniranjan.github.io/gci18.fossasia.org/

**Comment by YashKumarVerma** [comment]
1. do we actually need to edit so many files to add a page.
2. can the purple box be made complete ***misses bottom line***
3. Consider changing the purple color to grey.

The color code is #292929

**Comment by niteshkumarniranjan** [comment]
1. Yep I have created the _include files to avoid repetition of header and footer if we will change something  in a page we have to change that again on every page this is for code management
2. That Line is from my portfolio website screenshot it's not from gci website.
3.
4. I have removed them.

**Comment by niteshkumarniranjan** [comment]
Please check my repo: https://github.com/niteshkumarniranjan/gci18.fossasia.org

**Comment by YashKumarVerma** [comment]
with many files, i meant the addition of ~150+ files.
image

**Comment by YashKumarVerma** [comment]
the grey color to match the theme ?

**Comment by niteshkumarniranjan** [comment]
I think I have done a mistake in squashing the commits. I'm really sorry! :disappointed: What should I do?

**Comment by YashKumarVerma** [comment]
git rebase

**Comment by niteshkumarniranjan** [comment]
and the color is from my website I have to change it in my portfolio

**Comment by niteshkumarniranjan** [comment]
Oops! I'm sorry I haven't done any mistake that many file changes is because of deletion of PHP files.

**Comment by abishekvashok** [comment]
Hey, no need to worry.

It seems that you are solving many issues in a single pr. You can use multiple branches for that, and send different PRs for each issues from those branches. :)

**Comment by YashKumarVerma** [comment]
Please merge commits.

**Comment by abishekvashok** [comment]
@YashKumarVerma let's make this work and then decide on the colour. :')

**Comment by niteshkumarniranjan** [comment]
Creating PR for Each Issues.

**Pull request closed without merging**
