### PR TITLE
Fixed the social media icons 

### LINKED ISSUE #492: social media links are not showing [because of overwrititng the ( .fa ) class]
**Actual Behaviour**

screenshot_2018-11-25 google code-in with fossasia 2018

**Expected Behaviour**
screenshot_2018-11-25 google code-in with fossasia 2018 1

PROBLEM
social media links icon are not showing up

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by subhahu123**
- [ ] Included a Preview link and screenshot showing after and before the changes.
- [ ] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

Removing the extra classes which are overlapping the past .fa class
i have checked everything with that everything is working fine all.css does not require and if require it should be placed properly 
according to me it's working fine without that class

preview link : http://niec.ml/

- Fixes  #492

## Description / Changes
 
removal  of extra all.css class which was overwriting the other classes

### Before:

screenshot_2018-11-25 google code-in with fossasia 2018

### After:

screenshot_2018-11-25 google code-in with fossasia 2018 1

- - - - - - - - - - - -

### CODE REVIEW

**Comment by pythongiant** [comment]
can a mentor revert this? its breaking the social media section

**Comment by subhahu123** [comment]
@pythongiant  please screen shot please about which section u r talking

**Comment by pythongiant** [comment]
@subhahu123 
image
Notice how the slack icon is out of shape?

**Comment by pythongiant** [comment]
image
Versus the original one

**Pull request merged**
