### PR TITLE
Changed The UI and Added few more More Sections.. Fixes ( #49 , #41 , #47 )

### PR DESCRIPTION
**Pull request by Sid911**
Please read and understand everything below

- [x] Included a screenshot showning after and before the changes.
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request 

- Fixes:#49 Fixes:#41 Fixes:#47 
- Added Links to Social Accounts of Fossasia
- Added (Me) Student In Student's section
- Removed some extra non-required parts of the website.
_I was not able to test 51 for some reason_
## Description / Changes

-The Navbar is now Transparent (Light Pictures Make it harder to read, the first Picture In The Slideshow is to be removed/edited for better visiblity
-Added a little information about "what open-source is?" for someone who is new.
-Added a dedicated section for social Media links
-Changed the layout of students and Mentor section
-Added `target="_new"` for opening the links in new tab in students section
-removed almost all the template defaults (few are still there for placeholder use, if anyone wants to replace them.... Like the video)
-removed the news section from footer
-added social media links in footer

##To Be Done
-Change the logo in light theme
-Remove Unused sections in navbar

##Before
image

image

image

image

##AFTER
image

image

image

image

### CODE REVIEW

**Comment by Sid911** [comment]
I would like to know if this one pull request can be considered in more than one task 😊 because I merged them all up

**Comment by saarthakchats** [comment]
Actually, they prefer different PRs

**Comment by saarthakchats** [comment]
But depends on the type of task

**Comment by myfrom** [comment]
A few suggestions:
 - You shouldn't use `target="_new"`, it is outside of the spec, you should use `target="_blank"` [(link)](https://stackoverflow.com/a/4964223/6166832)
 - For security purposes, it's recommended to add `rel="noopener noreferrer"` to _target blank_ links [(link)](https://mathiasbynens.github.io/rel-noopener/)

**Comment by Sid911** [comment]
Thank you... I will keep that in mind from next time 😊

**Comment by realslimshanky** [comment]
There should be a separation of concern between pull requests. One pull request should only solve one problem. More than one solution in any pull request would be hard to debug in history. I would strongly recommend it.

**Comment by Sid911** [comment]
I don't know but rebaseing doesn't work... Then the code gets errors and things like that.

I am going to close this pulland make different ones for different concerns

I am wondering if upstream would be better.

**Pull request closed without merging**
