### PR TITLE
Add more 6 Mentors

### PR DESCRIPTION
**Pull request by niteshkumarniranjan**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Preview Link https://niteshkumarniranjan.github.io/gci18.fossasia.org/

## Description / Changes
Added more 6 Mentors

screenshot from 2018-10-28 17-04-03

### CODE REVIEW

**Comment by niteshkumarniranjan** [comment]
@akshatnitd Which issue should I address If I will create a issue then It will never close because there many more mentors in the community.

**Comment by akshatnitd** [comment]
@niteshkumarniranjan Yes, that issue would be open until all the mentors are added. Please add only 1 mentor in the PR.

**Comment by niteshkumarniranjan** [comment]
@akshatnitd in past I have already added a mentor so I think we should close this PR.

**Comment by akshatnitd** [comment]
@liveHarshit This PR was supposed to be closed, why was it merged?

**Comment by liveHarshit** [comment]
@Akshat-Jain I was really my mistake, sorry for that. Next time I will take care of all the reviews.

**Pull request merged**
