### PR TITLE
New student added

### PR DESCRIPTION
**Pull request by jakubpawlina**
Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`
- Preview Link
-

### CODE REVIEW

**Comment by jakubpawlina** [comment]
Before:
before1
After:
after1
Link:
[jakubpawlina.github.io/gci18-fossasia](https://jakubpawlina.github.io/gci18-fossasia/)

**Comment by jakubpawlina** [comment]
Screenshot of my work:
zrzut ekranu 63

**Comment by jakubpawlina** [comment]
### Changes done in this Pull Request

- uploaded a picture for student Jakub Pawlina
- new student (Jakub Pawlina) added to the website

**Comment by jakubpawlina** [comment]
Excause me, but how can I do that? Do I have to have locally installed git?

**Comment by jakubpawlina** [comment]
Excause me, but how I can do that? Do I have to have git installed?

**Comment by fragm3** [comment]
@jakubpawlina you can see https://davidwalsh.name/squash-commits-git for rebasing commits.

**Comment by jakubpawlina** [comment]
@fragm3 thank you :) it was really helpful

**Comment by jakubpawlina** [comment]
@YashKumarVerma  I squashed changes. I hope everything is ok.  I was doing it first time, so I'm sorry for possible mistakes.

**Comment by jakubpawlina** [comment]
Thank you!

**Pull request merged**
