### PR TITLE
Added Student Project : Tick

### PR DESCRIPTION
**Pull request by pythongiant**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://pythongiant.github.io/gci18.fossasia.org/projects.html)

## Description / Changes
Added Project Tick to student project section

## Screenshots if any:

screenshot

- - - - - - - - - - - -

### CODE REVIEW

**Comment by pythongiant** [comment]
umm @sarnava1 have you tried looking here https://pythongiant.github.io/gci18.fossasia.org/ 
works fine

**Comment by pythongiant** [comment]
Done!

**Comment by sarnava1** [comment]
@pythongiant I looked into you preview link as well and found out the same problem!!!

**Comment by pythongiant** [comment]
i think @sarnava1 its a problem with your browser

**Comment by sarnava1** [comment]
@pythongiant let me see!!

**Pull request merged**
