### PR TITLE
[Fixed #229] Make map responsive 

### LINKED ISSUE #229: Map isn't responsive!
**Actual Behaviour**

map isn't responsive. It overflows. 
image

**Expected Behaviour**

Make it responsive

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by STEdirisuriya**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
- https://stedirisuriya.github.io/gci18.fossasia.org/
- Make map responsive 
- #229

### CODE REVIEW

**Comment by sk9331657** [comment]
@STEdirisuriya  Pull again the latest codebase.

**Comment by STEdirisuriya** [comment]
@sk9331657 OK, I did it. Thank you!

**Comment by STEdirisuriya** [comment]
@fragm3 Could you please see the image I attached in the issue? I tried to resize my browser window.  When I'm resizing it I saw the map only showing half. The right side part is overlapped.

**Comment by fragm3** [comment]
@STEdirisuriya which browser are you using?

**Comment by STEdirisuriya** [comment]
@fragm3 Google Chrome

**Comment by rpotter12** [comment]
@fragm3 In mobile phones map is not working properly. This PR solving that problem.

**Comment by rpotter12** [comment]
@STEdirisuriya update your fork too. Latest changes are not there in your preview link

**Comment by STEdirisuriya** [comment]
@rpotter12 I updated my fork now. Could please review it again?

**Pull request merged**
