### PR TITLE
Added Shubham Kumar as a Mentor

### LINKED ISSUE #7: Create a mentors section
We just added a new template
Create a mentors section in the current template with the same design.

The goal would be to create a mentor section, add a mentors.yml file, define a standard format, and make a mentor appear beautifully in the site using Jekyll.

_note: be sure to ask mentors before posting any of their details_

Ref: https://GitHub.com/fossasia/gci17.fossasia.org

### PR DESCRIPTION
**Pull request by sahildav**
Fixes #7 

screenshot from 2018-10-24 10-57-12

Added Link https://sahildav.github.io/gci18.fossasia.org/

### CODE REVIEW

**Comment by sahildav** [comment]
@abishekvashok  Please review.

**Comment by sahildav** [comment]
@ms10398  I have added a link for this pull request ,Please review.

**Comment by sahildav** [comment]
@ms10398  This can be now merged.

**Comment by STEdirisuriya** [comment]
No send a viewable link for your site.

**Comment by sahildav** [comment]
> No send a viewable link for your site.

https://sahildav.github.io/gci18.fossasia.org/

**Comment by ms10398** [comment]
If you look at the issue states that you should use yaml and Jekyll for it instead of adding static

**Comment by sahildav** [comment]
@ms10398 Ok  Here is the new Pr actually I made a seprate branch . Head Over it https://github.com/fossasia/gci18.fossasia.org/pull/14

**Pull request closed without merging**
