### PR TITLE
Sort contributors by contributions

### LINKED ISSUE #288: Contributors Section is Not Ordered Properly
**Actual Behaviour**

The contributors section is not ordered correctly by number of contributions. It randomizes each time the page is refreshed

##Trial 1:
screen shot 2018-11-09 at 12 30 16 pm
##Trial 2:
screen shot 2018-11-09 at 12 30 33 pm

**Expected Behaviour**

The ordering should be consistently sorted by number of contributions.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ngmhprogramming**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Sort contributors by contributions
- [Preview Link](https://ngmhprogramming.github.io/gci18.fossasia.org/)
- Contributors do not show at times, because API limit is exceeded

- Fixes #288 

## Description / Changes

Contributors on the contribution page were not sorted by contributions at first, but now they are.

### Before:
Before
### After:
After

- - - - - - - - - - - -

### CODE REVIEW

**Comment by ngmhprogramming** [comment]
Isn't it sorted because i fixed it

**Comment by jogendra** [comment]
@ngmhprogramming No, they are already sorted without merging this code. see https://gci18.fossasia.org/#contributors

**Comment by ngmhprogramming** [comment]
I just checked it and it is not sorted.

**Comment by ngmhprogramming** [comment]
Not Sorted

**Comment by ngmhprogramming** [comment]
The first 2 people has 12 appear before 16!

**Pull request merged**
