### PR TITLE
Format js files

### LINKED ISSUE #297: Format JavaScript files
**Actual Behaviour**

js files arent formatted

**Expected Behaviour**

format them

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by ammarbinfaisal**
- [x] Included a Preview link.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

Ran `prettier --single-qoute --write filename`
I used single-qoute flag because the files here are generally using single qoutes.
if there's anything other than this is required then plz let me know

- Fixes #297 
- [Preview link](https://ammarbinfaisal.github.io/gci18)

### CODE REVIEW

**Comment by Ryan10145** [comment]
@ammarbinfaisal Please resolve the conflicts.

**Comment by ammarbinfaisal** [comment]
@fragm3 won't it be better to ask the person whose PR you all are going to accept next to run prettier on the js files? otherwise I'll have to do this again and again

**Comment by fragm3** [comment]
@ammarbinfaisal resolve conflict

**Comment by ammarbinfaisal** [comment]
@fragm3 done

**Comment by ammarbinfaisal** [comment]
@realslimshanky sorry for replying so late.
### Screenshot
gci18site

**Pull request merged**
