### PR TITLE
Adding logos to Readme.md file

### PR DESCRIPTION
**Pull request by subhahu123**
# Changes done in this Pull Request
Adding logos to readme.md file
adding new folder logo to img with two new logos file

screenshot from 2018-11-26 23-24-38

### CODE REVIEW

**Comment by subhahu123** [comment]
@jogendra review this
@abishekvashok

**Comment by subhahu123** [comment]
@nikit19  this does not look good

screenshot from 2018-11-27 01-47-54

Now what can i do is remove the fossasia logo or if u can provide or commit on my patch with 
fossasia logo which looks good to it

**Comment by subhahu123** [comment]
Please provide screenshot or  link of logo

**Comment by STEdirisuriya** [comment]
There are already original FOSSASIA logos in the repo, you can link them on the readme.md without adding new.

**Comment by subhahu123** [comment]
@STEdirisuriya  can u tell me file path or name

**Pull request closed without merging**
